/**********************************************************************
 * Extern for blockstack
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var blockstack = {
    "BLOCKSTACK_GAIA_HUB_LABEL": {},
    "CreativeWork": function () {},
    "Organization": function () {},
    "Person": function () {},
    "Profile": function () {},
    "config": {
      "logLevel": {},
      "network": {
        "DUST_MINIMUM": {},
        "blockstackAPIUrl": {},
        "broadcastServiceUrl": {},
        "btc": {
          "utxoProviderUrl": {}
        },
        "excludeUtxoSet": {},
        "includeUtxoMap": {},
        "layer1": {
          "bech32": {},
          "bip32": {
            "private": {},
            "public": {}
          },
          "messagePrefix": {},
          "pubKeyHash": {},
          "scriptHash": {},
          "wif": {}
        }
      }
    },
    "connectToGaiaHub": function () {},
    "containsValidAddressProofStatement": function () {},
    "containsValidProofStatement": function () {},
    "decodeToken": function () {},
    "decryptContent": function () {},
    "deleteFile": function () {},
    "doPublicKeysMatchIssuer": function () {},
    "doPublicKeysMatchUsername": function () {},
    "doSignaturesMatchPublicKeys": function () {},
    "ecPairToAddress": function () {},
    "ecPairToHexString": function () {},
    "encryptContent": function () {},
    "extractProfile": function () {},
    "fetchAppManifest": function () {},
    "generateAndStoreTransitKey": function () {},
    "getAddressFromDID": function () {},
    "getAppBucketUrl": function () {},
    "getAuthRequestFromURL": function () {},
    "getAuthResponseToken": function () {},
    "getCoreSession": function () {},
    "getDIDType": function () {},
    "getEntropy": function () {},
    "getFile": function () {},
    "getPublicKeyFromPrivate": function () {},
    "getTokenFileUrl": function () {},
    "getTransitKey": function () {},
    "getUserAppFileUrl": function () {},
    "handlePendingSignIn": function () {},
    "hexStringToECPair": function () {},
    "isExpirationDateValid": function () {},
    "isIssuanceDateValid": function () {},
    "isLaterVersion": function () {},
    "isManifestUriValid": function () {},
    "isRedirectUriValid": function () {},
    "isSameOriginAbsoluteUrl": function () {},
    "isSignInPending": function () {},
    "isUserSignedIn": function () {},
    "loadUserData": function () {},
    "lookupProfile": function () {},
    "makeAuthRequest": function () {},
    "makeAuthResponse": function () {},
    "makeCoreSessionRequest": function () {},
    "makeDIDFromAddress": function () {},
    "makeDIDFromPublicKey": function () {},
    "makeECPrivateKey": function () {},
    "makeProfileZoneFile": function () {},
    "makeUUID4": function () {},
    "network": {
      "BitcoindAPI": function () {},
      "BlockchainInfoApi": function () {},
      "BlockstackNetwork": function () {},
      "InsightClient": function () {},
      "LocalRegtest": function () {},
      "defaults": {
        "LOCAL_REGTEST": {
          "DUST_MINIMUM": {},
          "blockstackAPIUrl": {},
          "broadcastServiceUrl": {},
          "btc": {
            "bitcoindCredentials": {
              "password": {},
              "username": {}
            },
            "bitcoindUrl": {}
          },
          "excludeUtxoSet": {},
          "includeUtxoMap": {},
          "layer1": {
            "bech32": {},
            "bip32": {
              "private": {},
              "public": {}
            },
            "messagePrefix": {},
            "pubKeyHash": {},
            "scriptHash": {},
            "wif": {}
          }
        },
        "MAINNET_DEFAULT": {
          "DUST_MINIMUM": {},
          "blockstackAPIUrl": {},
          "broadcastServiceUrl": {},
          "btc": {
            "utxoProviderUrl": {}
          },
          "excludeUtxoSet": {},
          "includeUtxoMap": {},
          "layer1": {
            "bech32": {},
            "bip32": {
              "private": {},
              "public": {}
            },
            "messagePrefix": {},
            "pubKeyHash": {},
            "scriptHash": {},
            "wif": {}
          }
        }
      }
    },
    "nextHour": function () {},
    "nextMonth": function () {},
    "nextYear": function () {},
    "profileServices": {
      "facebook": function () {},
      "github": function () {},
      "hackerNews": function () {},
      "instagram": function () {},
      "linkedIn": function () {},
      "twitter": function () {}
    },
    "publicKeyToAddress": function () {},
    "putFile": function () {},
    "redirectToSignIn": function () {},
    "redirectToSignInWithAuthRequest": function () {},
    "redirectUserToApp": function () {},
    "resolveZoneFileToPerson": function () {},
    "resolveZoneFileToProfile": function () {},
    "safety": {
      "addressCanReceiveName": function () {},
      "isInGracePeriod": function () {},
      "isNameAvailable": function () {},
      "isNameValid": function () {},
      "isNamespaceAvailable": function () {},
      "isNamespaceValid": function () {},
      "namespaceIsReady": function () {},
      "namespaceIsRevealed": function () {},
      "ownsName": function () {},
      "revealedNamespace": function () {}
    },
    "sendCoreSessionRequest": function () {},
    "signProfileToken": function () {},
    "signUserOut": function () {},
    "transactions": {
      "BlockstackNamespace": function () {},
      "estimateAnnounce": function () {},
      "estimateNameImport": function () {},
      "estimateNamespacePreorder": function () {},
      "estimateNamespaceReady": function () {},
      "estimateNamespaceReveal": function () {},
      "estimatePreorder": function () {},
      "estimateRegister": function () {},
      "estimateRenewal": function () {},
      "estimateRevoke": function () {},
      "estimateTransfer": function () {},
      "estimateUpdate": function () {},
      "makeAnnounce": function () {},
      "makeBitcoinSpend": function () {},
      "makeNameImport": function () {},
      "makeNamespacePreorder": function () {},
      "makeNamespaceReady": function () {},
      "makeNamespaceReveal": function () {},
      "makePreorder": function () {},
      "makeRegister": function () {},
      "makeRenewal": function () {},
      "makeRevoke": function () {},
      "makeTransfer": function () {},
      "makeUpdate": function () {}
    },
    "updateQueryStringParameter": function () {},
    "uploadToGaiaHub": function () {},
    "validateProofs": function () {},
    "verifyAuthRequest": function () {},
    "verifyAuthRequestAndLoadManifest": function () {},
    "verifyAuthResponse": function () {},
    "verifyProfileToken": function () {},
    "wrapProfileToken": function () {}
  };
  /**********************************************************************
   * End Generated Extern for blockstack
  /**********************************************************************/